### ISSUE TITLE
Improve reader & general HTML/JS

### ISSUE THREAD

**Issue by Frain-Breeze** [RicterZ/nhentai#111]
Because of the way --gen-main makes it's database (plain javascript, not made for that AT ALL) it take long to load, and most mobile devices won't even display it.
possible fixes would be:
-create lookup tables for tags
-switch to SQlite database for storing image metadata

lookup tables aren't too hard, but still not as fast as wanted really
switching to SQlite requires quite some work, but it would improve performance quite a bit.
[SQlite for browser (.js implementation)](https://github.com/sql-js/sql.js)
SQlite is also a standard lib for python

Reader improvements would also be nice, like options to:
-fit image to screen (no more scrolling)
-hide sidebar (for mobile devices)
-save doujin to custom "list" (like nhentai's favorites)

**Comment by RicterZ** [comment]
About the webpage, maybe you can @Alocks :P

**Comment by Alocks** [comment]
My original idea was to create a lookup table but didn't end well since the browser block by default local file access.

I'm not a front-end guy, so, about the reader options I don't think I'll be able to do a good work with the page, so, sorry I won't budge (I hate front-end Lol).

by making a database i don't think would take much time to develop, since is just delete and create again the table everytime you run --gen --main.
 I Will try implementing next week. By doing that should be also possible to save favorite doujins also

**Comment by RicterZ** [comment]
I had already released version 0.3.9 with these features :P


Alocks <notifications@github.com> 于 2020年4月21日周二 上午12:59写道：

**Comment by Alocks** [comment]
Oh nice, gotta look into it
