### ISSUE TITLE
Sort by language not working properly.

### ISSUE THREAD

**Issue by kilpsz** [RicterZ/nhentai#121]
When i use 

nhentai -D --language english --tag "lolicon, humiliation"  -o F:\Nhentai\loli -t 15 --format '[%t]%a' --page=1 

 it does couple of different things, 

1.  -o F:\Nhentai\loli will for some reason download them into F:Nhentailoli folder.

2. --language english doesn't work/do anything.

i also tried --language=English (it shows to use this in --help) but that didn't do anything either

-

nhentai -D --tag "loli"  -o F:\Nhentai\loli -t 15 --format '[%t]%a' --page=1

Doesn't work at all https://i.imgur.com/rZNu7va.png

while this one does

nhentai -D --tag "loli, humiliation"  -o F:\Nhentai\loli -t 15 --format '[%t]%a' --page=1

 https://i.imgur.com/WLUqRAn.png

The only time --language english seems to work is when you're not trying to search anything else as it will use that as a tag.

**Comment by Alocks** [comment]
tags needs to be written perfectly as is in the site since is a json request. Type lolicon instead.
![Capturar](https://user-images.githubusercontent.com/8052065/80842046-05d07b00-8bd7-11ea-82bc-f6e0830fed80.JPG)

Will debug language command. Has been edited recently so it's probably a bug, or maybe case-sensitive

**Comment by Alocks** [comment]
Found the bug. All options are broken because --l command.
For now use -l="english, lolicon". Someone made a huge change and didn't document about it.
Use "tag", if you use 'tag' it won't work. I guess I'll remove all --tag options and leave --l wich makes easier, and change how  --language works to to have no need to type every time.
