### ISSUE TITLE
Download favourite doujinshi

### ISSUE THREAD

**Issue by RicterZ** [RicterZ/nhentai#13]

**Comment by linuxdude96** [comment]
OMG this is so cool thank you @RicterZ

**Comment by RicterZ** [comment]
I pushed some commits, you can clone the project then try it now.

**Comment by linuxdude96** [comment]
thanks again I am going to try it out tonight.

**Comment by linuxdude96** [comment]
Alright I just downloaded it. It's pretty awesome! Thanks for doing this again.

**Comment by linuxdude96** [comment]
Alright I love it so fare and downloaded a group of doujin already as a test. The only issue, I can see is it naming the files as the ID. Can you on the next release have it pull down name of the doujin instead of the ID? I am going to use this in about a month to download over 500+ pieces of doujin for my plex server.

**Comment by RicterZ** [comment]
OK, it's a easy work

**Comment by linuxdude96** [comment]
thanks again your fantastic.  Your project has serious potential.

**Comment by RicterZ** [comment]
Hi, now it can save downloaded doujinshi as the doujinshi name.

**Comment by RicterZ** [comment]
WTF...

**Comment by linuxdude96** [comment]
what wrong?

**Comment by linuxdude96** [comment]
also thanks again, I will check it out once. I get off work.
