### ISSUE TITLE
about "cf_clearance cookie and useragent" question

### ISSUE THREAD

**Issue by xcbrr45** [RicterZ/nhentai#253]
how is this actually implemented to the CLI ? 
`--user-agent=USERAGENT`

so i set up 
`--cookie="cookies.txt`
`--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0`

but im still getting:
`[ERROR] Blocked by Cloudflare captcha, please set your cookie and useragent`

Apologies since im not really into programming , but i do use your tool way back on early 2021 and is really helpful on archiving stuff

**Comment by JengRung** [comment]
I am having the same issue, how did you end up solving this problem?

**Comment by SandyRodgers-2017** [comment]
> I am having the same issue, how did you end up solving this problem?

If you are still having a problem don't use cookie.txt file. You should instead be copy and use these that you can find by pressing f12 and going to storage.
The values you want are csrftoken, sessionid, and cf_clearance
	nhentai --cookie="csrftoken=[csrftoken value];sessionid=[sessionid value];cf_clearance=[cf_clearance value]"
after you have plugged in each of those values hit enter and you should now be able to sign in. At times this may not work and could be due to nhentai site owners increasing cloudflares sensitivity to bots.

**Comment by RicterZ** [comment]
Crawlers are not welcome to nhentai.net now.... It's hard to bypass against Cloudflare WAF
