### ISSUE TITLE
Cannot Get Username

### ISSUE THREAD

**Issue by Emhyr-var-emris** [RicterZ/nhentai#254]
Hi, I'm rather new to Github and all this. I tried following all the steps provided with this tool, but I always get stuck at the cookie part.
I would finish manual installation and type in my cookie:

     nhentai --cookie "csrftoken=########; sessionid=#######; cf_clearance=######"
[](url)
and fill in my useragent in similar fashion: 

     nhentai --useragent "useragent=########"

But no matter what, after I try to download my favorites I keep getting either this message: 

           [06:56:36] [INFO] Using mirror: https://nhentai.net
           [06:56:36] [INFO] Using viewer template "default"
           [06:56:37] [WARNING] Cannot get your username, please check your cookie or use `nhentai --cookie` to set your cookie
           [06:56:37] [ERROR] Can't get your number of favorited doujins. Did the login failed?
           [06:56:37] [INFO] All done.

I'm inputting the values I found in the developer's kit associated with each respective cookie, was that incorrect? Did I miss a step? I'd love some insight. Thanks!

**Comment by MarDeny** [comment]
I have similar issue. What is strange when i was using this app previously all was working fine.

**Comment by SalvationThroughAcidRain** [comment]
I had the same exact problem (or at least, a very similar one). Fortunately, I solved it, and was able to download doujinshi individually, and my favorites altogether.

I’ll detail all the steps I took. 

Note: the commands I wrote will be within opening and closing brackets. Example: [I wrote this.]. Also, naturally, I’m assuming you already installed this GitHub tool (I did so manually, and through pip, on a separate occasion). Even if you completed most of these steps, read through just in case you missed something. It’s somewhat verbose, but I want to be comprehensive with this post, and "cover all bases." I installed the latest version of Python beforehand, by the way (3.10.6). Any commands advised to write “python’ had to be replaced by “python3,” even though that won’t be otherwise present in this post (I write this just in case it might help in the future).

Beginning of step-by-step guide:

**Step 0**: Firstly, I’m not sure if this was really necessary, but just in case, I made sure to, in the MacOS terminal, deploy this command: 

[pip install --upgrade nhentai]. 

Again, I’m not sure if this is necessary, so don't deploy it unless nothing else works, I suppose.

**Step 1**: I experienced difficulty with Google Chrome, so I switched to Firefox, updated it, and found success with the latter browser which I did not find with the former. I recommend trying Firefox if you haven’t already, and ensuring that it’s updated.

**Step 2**: Sign into your nHentai account on Firefox. Then click the three horizontal lines at the top right (☰), click on “Web Developer,” and finally, click on “Storage Inspector.” The “Cookies” tab on the left side and the bottom screen that just popped up should have automatically expanded, showing below, next to a globe icon, “https://nhentai.net," opening a sheet with columns titled “Name,” “Domain,” etc. You’re looking for the two columns titled “Name,” and “Value.” Correspond “cf_clearance,” “csrftoken,” and “sessionid” with their respective values a couple columns to the right. 
Copy these values, and paste them within the respective “zzz’s” in the following command line, and deploy it: 

[nhentai --cookie "csrftoken=zzz; sessionid=zzz; cf_clearance=zzz”]. 

**Step 3**: Go to this link: https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes. It should provide you with your User Agent. Copy all of the text within the box titled “Parse a User agent.” With this copied User Agent text, replace the “zzz” in the following command, and deploy it: 

[nhentai --useragent="zzz”].

**Step 4**: That should be it. Now to see if you can download doujinshi. Deploy this command, replacing the “zzzzzz” with a preferred nhentai six-number code: 

[nhentai --id=zzzzzz].

End of step-by-step guide. I hope this helps, and good luck!

P.S. I'm not sure if this matters at all– it's honestly simply conjecture. But if, after all of this, it still doesn't work, it might work if you log out, and sign in again to nHentai, and trigger a Captcha that you have to complete to sign in once more. If that changes anything, then it might solve any problems you might have. Again, purely conjecture.

**Comment by MarDeny** [comment]
I followed instructions from SalvationThroughAcidRain. 
--It working now. What i suppose was a reason it was user agent format or error when i entered it. 
--Another option could be loging in and off nhentai. (I was before clearing cookies but this was not working for me) 
--Version was correct no update proceed.
