### ISSUE TITLE
Type Error When Trying To Download Anything

### ISSUE THREAD

**Issue by spyball4** [RicterZ/nhentai#361]
In running a variant of the example command (or any other command that would prompt a download, I get the following error for line 152 in doujinshi_parser on a Linux Debian VM.
`TypeError: NoneType object is not callable `

![image](https://github.com/user-attachments/assets/9562cd7d-3af3-482e-868c-38d2777abcf6)

**Comment by spyball4** [comment]
Forgot to add that I am on the latest commit: [bb41e50](https://github.com/RicterZ/nhentai/commit/bb41e502c1cf5d772f61311bab36e824dd591f2e)

**Comment by RicterZ** [comment]
It's weird....Could you post a screenshot of the source code of `doujinshi_parser` function during line 140-160?

**Comment by RicterZ** [comment]
I pushed

**Comment by spyball4** [comment]
Confirmed that pulling and running setup.py fixes this and the downloads work! Thank you

**Comment by benedrill** [comment]
> And try commit [1f3528a](https://github.com/RicterZ/nhentai/commit/1f3528afad5eb6f5f2406429692b78af0840732d)

This ends up taking some html as well. This is from the generated metadata.json file:
`"favorite_counts":"<span class=\"nobold\">(<span class=\"count\">48545</span>)</span>"`

 When not using any cookies, it returns "None" instead despite favorites being non-zero. This is because there is no `<span class="count">` tag within `<span class="nobold"/>` when not logged in:
`"favorite_counts":"<span class=\"nobold\">(48421)</span>"`

I think this should be able to take care of both cases:
```
favorite_counts = doujinshi_info.find('span', class_='nobold').text.strip("(|)")
...
doujinshi['favorite_counts'] = favorite_counts
```
Also, is there a reason why `favorites_count` is stored as a string in `metadata.json`? I think it being stored as int just like `pages` would make more sense.
