### ISSUE TITLE
Downloading doujins by parodies 

### ISSUE THREAD

**Issue by BetterWaifus** [RicterZ/nhentai#82]
Is it possible to download all the doujins that are a parody of a certain thing?

**Comment by BetterWaifus** [comment]
You currently cannot do this right?
I looked through all the options and none seem to be search by parody.

**Comment by RicterZ** [comment]
I'll check it out

BetterWaifus <notifications@github.com> 于 2019年8月3日周六 上午11:40写道：

**Comment by aikoofujimotoo** [comment]
It is actually possible. nhentai provide finer search queries such as `parody:"to love-ru"`. You can use that as a search query.

**Comment by Alocks** [comment]
Reading the code, the issue is that  only looks for [TAG_URL](https://nhentai.net/tags/)...
I'm wodering which would be the best approach...

- Add options for --artist --parody, --characters,--group
- changing TAG_URL string to a list, and add links for each of them
- Add an argument in parser.tag_parser(), `index` for `TAG_URL[index]`
- Look up to add multiple tags?

**Comment by Alocks** [comment]
Reading the code, the issue is that only looks for TAG_URL...
I'm wodering which would be the best approach...

- Add options for --artist --parody, --characters,--group
- changing TAG_URL string to a list, and add links for each of them
- Add an argument in parser.tag_parser(), index for TAG_URL[index]
- Look up to add multiple tags?

Added command --parody and other things
Waiting for pull #84
